import {
  AlarmClock,
  Armchair,
  Baby,
  Backpack,
  Bath,
  BedDouble,
  Bike,
  Blinds,
  BookOpen,
  Briefcase,
  Building2,
  Camera,
  Car,
  ChefHat,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Cpu,
  Dog,
  DoorOpen,
  Drill,
  Droplets,
  Dumbbell,
  Fan,
  Flower2,
  Gamepad2,
  Gift,
  GlassWater,
  Hammer,
  Heart,
  Home,
  LampFloor,
  Laptop,
  Lightbulb,
  Lock,
  Luggage,
  Microwave,
  Monitor,
  Mountain,
  Package,
  PaintRoller,
  Palette,
  PawPrint,
  PencilRuler,
  Phone,
  PiggyBank,
  Plane,
  Plug,
  Printer,
  Refrigerator,
  Router,
  Shirt,
  ShowerHead,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Speaker,
  Star,
  Store,
  Table,
  Tent,
  Thermometer,
  Trash2,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Warehouse,
  WashingMachine,
  Wrench,
} from "lucide-svelte";

export type IconComponent = typeof Wallet;

export const BUDGET_ICONS: Record<string, IconComponent> = {
  wallet: Wallet,
  home: Home,
  "piggy-bank": PiggyBank,
  building: Building2,
  house: Home,
  plane: Plane,
  car: Car,
  mountain: Mountain,
  tent: Tent,
  heart: Heart,
  gift: Gift,
  baby: Baby,
  book: BookOpen,
  sparkles: Sparkles,
  briefcase: Briefcase,
  paw: PawPrint,
  store: Store,
  umbrella: Umbrella,
  bike: Bike,
  star: Star,
  camera: Camera,
};

export const CATEGORY_ICONS: Record<string, IconComponent> = {
  "chef-hat": ChefHat,
  sofa: Sofa,
  "bed-double": BedDouble,
  hammer: Hammer,
  tv: Tv,
  fridge: Refrigerator,
  lamp: LampFloor,
  armchair: Armchair,
  table: Table,
  "door-open": DoorOpen,
  "paint-roller": PaintRoller,
  curtain: Blinds,
  bath: Bath,
  "shower-head": ShowerHead,
  sink: Droplets,
  "washing-machine": WashingMachine,
  microwave: Microwave,
  coffee: Coffee,
  utensils: Utensils,
  "glass-water": GlassWater,
  warehouse: Warehouse,
  package: Package,
  plug: Plug,
  lightbulb: Lightbulb,
  lock: Lock,
  wrench: Wrench,
  drill: Drill,
  broom: Trash2,
  shirt: Shirt,
  backpack: Backpack,
  luggage: Luggage,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  smartphone: Smartphone,
  router: Router,
  plant: Sprout,
  flower: Flower2,
  "alarm-clock": AlarmClock,
  thermometer: Thermometer,
  droplets: Droplets,
  snowflake: Snowflake,
  fan: Fan,
  speaker: Speaker,
  gamepad: Gamepad2,
  clapperboard: Clapperboard,
  dumbbell: Dumbbell,
  dog: Dog,
  bike: Bike,
  truck: Truck,
  car: Car,
  pencil: PencilRuler,
  palette: Palette,
  phone: Phone,
  cpu: Cpu,
  "dollar": CircleDollarSign,
};

export const BUDGET_ICON_KEYS = Object.keys(BUDGET_ICONS);
export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

export function budgetIcon(key: string): IconComponent {
  return BUDGET_ICONS[key] ?? Wallet;
}

export function categoryIcon(key: string): IconComponent {
  return CATEGORY_ICONS[key] ?? Package;
}
